// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Bread: typeof import('./src/components/bread.vue')['default']
    Calendar: typeof import('./src/components/calendar/index.vue')['default']
    Editor: typeof import('./src/components/editor.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    PreviewImage: typeof import('./src/components/previewImage/previewImage.vue')['default']
    Routerview: typeof import('./src/components/routerview.vue')['default']
    Setting: typeof import('./src/components/setting.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    Sidebar_trigger: typeof import('./src/components/sidebar_trigger.vue')['default']
    Test: typeof import('./src/components/test.vue')['default']
  }
}

export { }
